name: Ensure PR from dev or release/

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if [[ ${GITHUB_HEAD_REF} != dev ]] && ! [[ ${GITHUB_HEAD_REF} =~ ^release/ ]];
          then
            echo "Error: Pull request must come from 'dev' or 'release/' branch"
            exit 1
          fi
