name: Ruff

on:
  pull_request:
    branches:
      - main

jobs:
  uv-ruff:
    name: ruff
    runs-on: ubuntu-latest

    steps:
        - uses: astral-sh/ruff-action@v3
          with:
            args: check --select E4,E7,E9,F,I --exclude __init__.py
        - run: ruff format
