name: Ruff

on:
  pull_request:
    branches:
      - main

jobs:
  uv-ruff:
    name: ruff
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set python version
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run ruff linter
        run: uv run ruff check --fix
      - name: Run ruff formatter
        run: uv run ruff format
