name: Sync dev with main

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  open-pr-main-to-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Open PR from main to dev
        env:
          GH_TOKEN: ${{ secrets.QUANTEM_BOT_PAT }}
          REPO: ${{ github.repository }}
        run: |
          # Check if PR already exists
          if gh pr list --head main --base dev --repo "$REPO" --json number --jq '.[0]'; then
            echo "PR from main to dev already exists. Skipping."
            exit 0
          fi

          # Create the pull request
          gh pr create \
            --repo "$REPO" \
            --head main \
            --base dev \
            --title "Sync main to dev" \
            --body "This PR syncs \`dev\` with \`main\` following a release."